service: TestService

plugins:
  - serverless-offline
  - serverless-localstack

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'local'}
  region: us-east-1
  endpointType: PRIVATE
  memorySize: 512
  deploymentBucket: localstack-packages
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sns:Subscribe
            - sns:Publish
          Resource:
            - "Fn::Join":
                - ":"
                - - "arn"
                  - Ref: "AWS::Partition"
                  - "sns"
                  - Ref: "AWS::Region"
                  - Ref: "AWS::AccountId"
                  - "local-notification-topic"
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:ListObjects
          Resource: arn:aws:s3:::localstack-packages

functions:
  main:
    handler: src/index.handler
    timeout: 300
    events:
      - sns:
          arn:
            Fn::Join:
              - ":"
              - - "arn:aws:sns"
                - Ref: "AWS::Region"
                - Ref: "AWS::AccountId"
                - "local-notification-topic"
          topicName: local-notification-topic

package:
  excludeDevDependencies: true

custom:
  serverless-offline:
    httpPort: 8089
    noPrependStageInUrl: true
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    debug: true
